### ISSUE TITLE
Rename as per smarty issue

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smirnoff99Frosst#12]
We need to rename to SMIRNOFF: https://github.com/open-forcefield-group/smarty/issues/193

**Comment by bannanc** [comment]
Repo name has been changed in pull request #35 
We'll need to update the conda install set up and the actual file names before this is complete.

**Comment by davidlmobley** [comment]
@bannanc - basically we need to change the package name, file names, etc. There's nothing specific for the conda install other than just pushing it to our channel once all the renaming is done and once we do a new "release" under "releases" from the code menu.

**Comment by bannanc** [comment]
Other than the labels inside the FFXML files (issue #44 ) I think we've finished renaming now.
