### ISSUE TITLE
Make forcefield conda installable

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smirnoff99Frosst#13]
Need to make it easy to install the latest version of the forcefield (rather than having it come along with `smarty` as at present: https://github.com/open-forcefield-group/smarty/pull/203)

**Comment by jchodera** [comment]
I think our plan should be:
* Finish and merge open `smarty` PR https://github.com/open-forcefield-group/smarty/pull/182 for GBSA support
* Split `smirnoff` forcefield tools into `open-forcefield-group/smirnoff`
* Have the `smirff99Frosst` repo and conda package install just the `ffxml` data files and require `smirnoff` as a dependency

**Comment by davidlmobley** [comment]
@jchodera - this sounds great if you can finish the GBSA support, otherwise we can go ahead with the second and third of those items without GBSA support. Let me know.

**Comment by davidlmobley** [comment]
@jchodera - did you still want to do the GBSA support ASAP, or should we proceed with the 2nd and 3rd bullet points and do GBSA later?

**Comment by bannanc** [comment]
Can we close this issue? This repo is now conda installable correct?

**Comment by davidlmobley** [comment]
Yes, thanks.
