### ISSUE TITLE
Missing some S-H bonds 

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smirnoff99Frosst#31]
There is only one S-H parameter in the current smirff99Frosst:
```
[#16X2:1]-[#1:2]                274.0  1.336   parm99 SH-HS
```
I think the best solution is to remove the X2 from the parameter above.

**Comment by davidlmobley** [comment]
Yes, agreed.

**Comment by bannanc** [comment]
added in pull request #43
