### ISSUE TITLE
Torsions around P-N (not in Parm99/Parm@Frosst)

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smirnoff99Frosst#32]
There is one P-N bond in the current smirff99Frosst with
```
[#15:1]-[#7:2]        300.0    1.65    smirff generic from Appl.Spec.,v57p970(2006)
121 [#15:1]=[#7:2]        400.0    1.5     smirff generic guess
```
However there are no torsions for rotations around those bonds. 

There are 138 lines for torsions around N~P bonds in GAFF2. I've started looking at them, but they are difficult to sort through. I'll try to post them once I've removed the obviously redundant parameters.

**Comment by davidlmobley** [comment]
Ha, wow. In terms of the GAFF2 parameters, I can imagine a couple possible outcomes:
1. You see some sort of consensus at least as to the general shape so we can adopt something perhaps halfway decent in terms of one or a couple of generics
2. There is no clear trend even in terms of general shape so we would be better off not covering this at all until we can do torsion fitting

**Comment by bannanc** [comment]
There are A LOT of the N-P torsions in GAFF2, but not a lot of them for the molecules in our filtered DrugBank set... In possibly more than post I'm going to 

1. explain what I did to try to understand the chemistry we're not covering
2. outline the types I found in gaff2.dat highlighting the ones that are most important for drugbank
3. and what I suggest we do for now and why in the 

No matter what we decide here, this is certainly something that will need to be looked at more closely. 

----------------------------------

# 1. Finding the missing Chemistry 

Since our goal was to cover the filtered DrugBank set (for now) I started by trying to type the GAFF2 mol2 files Daisy (our undergrad student) created for the off-ffcompare project. 
This allowed me to show GAFF2 atom types making it easier to look up the relevant torsions. 
Below I will show the 8 molecules with GAFF2 types assigned that were assigned generic N-P torsions. 
I'm not showing every missing torsion highlighted, there are multiple in each molecule (particularly those with multiple N-P bonds)

![dc66048f-ec5f-4cce-a9c0-7230d1ab7d06](https://cloud.githubusercontent.com/assets/11968541/24676378/9a804cc8-1937-11e7-9831-73e1b41d2ce3.png)

![db87622f-5b7a-4bb8-9589-dcbdd5ec44af](https://cloud.githubusercontent.com/assets/11968541/24676385/a3c110c4-1937-11e7-9c66-ac2b26722a69.png)

![9da1164c-a75e-43e4-b22f-466dea0c1a71](https://cloud.githubusercontent.com/assets/11968541/24676392/a740287a-1937-11e7-9866-a182151fb4e0.png)

![a4391260-18d5-492c-b251-3c5f850238ed](https://cloud.githubusercontent.com/assets/11968541/24676397/ac0de450-1937-11e7-8573-a850ed2a2b84.png)

![1576ece4-ee74-4672-b6b4-b5bfea1e04e4](https://cloud.githubusercontent.com/assets/11968541/24676405/b113ee04-1937-11e7-8cfe-be83b5ad17bc.png)

![f44353c1-a538-470c-aef4-f5c7fa5ba332](https://cloud.githubusercontent.com/assets/11968541/24676409/b53e72e2-1937-11e7-9cc4-fe81701e5eba.png)

![1a3d20ac-7980-4313-a014-25ce5760d00e](https://cloud.githubusercontent.com/assets/11968541/24676527/2a522754-1938-11e7-82ff-98a03b87a340.png)

![93122ad7-b00c-4c6d-a62b-b191e3d2c3bd](https://cloud.githubusercontent.com/assets/11968541/24676414/ba20e448-1937-11e7-9cf4-3b982a65e257.png)

**Comment by bannanc** [comment]
Please note I'm still editing the giant comment above, I keep posting it to save it... I'll tag people when I'm done

**Comment by bannanc** [comment]
Ok, I'm trying to look at the types for the other nitrogen types (not n3, n7, n8) in GAFF2. 
The easiest is sp3 with connectivity 4 since it doesn't have as many atom types as the sp2 nitrogens. so that's next:

#### Nsp3 with 4 bound atoms

That is atom types n4, nx, ny, nz in GAFF2.
Generic torsions:
```
X -n4-p2-X    3    0.500       180.000           3.000
X -n4-pe-X    3    0.500       180.000           3.000
X -n4-pf-X    3    0.500       180.000           3.000
X -n4-p3-X    6    0.900         0.000           3.000
X -n4-p4-X    4    0.200         0.000           3.000
X -n4-px-X    4    0.200         0.000           3.000
X -n4-p5-X    9    0.800         0.000           3.000
X -n4-py-X    9    0.800         0.000           3.000
```
Specific types:
```
c2-p2-n4-hn   1    0.000       180.000           3          c133 SS AUE=0.2623 RMSE=0.3265 TorType=3
c3-p3-n4-c3   1    0.067         0.000           3          c134 SS AUE=0.1760 RMSE=0.2433 TorType=3
c3-p4-n4-hn   1    0.005         0.000           3          c135 SS AUE=0.2627 RMSE=0.3254 TorType=3
os-p5-n4-c3   1    0.143         0.000           3          c136 SS AUE=0.4630 RMSE=0.6433 TorType=3
```
My rough estimate here:
```
[*:1]~[#7X4:2]-[#15:3]~[*:4]    1    0.1         0.000           3.000
```

-------
# Current Recommendations for N-P section 
```
[*:1]~[#7X3:2]-[#15:3]~[*:4]    1   2.5       180.000           2.000
[*:1]~[#7X4:2]-[#15:3]~[*:4]    1    0.1         0.000           3.000

[*:1]-[#7:2]-[#15:3]=[*:4]    1    3.000       180.0            -2.         TorType=1
[*:1]-[#7:2]-[#15:3]=[*:4]    1    2.300         0.0             3.         TorType=1

[#6X3:1]-[#7:2]-[#15:3]=[*:4]  1    0.000         0.0            -3.         TorType=1
[#6X3:1]-[#7:2]-[#15:3]=[*:4]   1    2.300         0.0             1.         TorType=1
```

**Comment by bannanc** [comment]
@davidlmobley I'm trying to look at sp2 nitrogens, but here is what I've done so far. 
@cbayly13 If you have time, any input would be appreciated

**Comment by cbayly13** [comment]
I like Caitlin's reasoning and I would add the following:
1. GAFF2 has many parameters for infrequent chemistry, drawing many fine distinctions in parameters. It smells of overfitting as a consequence of too many atom types (introduced elsewhere for other reasons) for too little chemistry. Automatic parameter fitting does the rest. So having few parameters is good.
2. Again because I smell overfitting, I would lose the second parameter (barrier 0.1) and see if it comes back down the road. The fifth parameter (zero barrier height) is vestigial and should simply be tossed.
3. Such a dramatic difference in torsion potential between `[*:1]-[#7:2]-[#15:3]=[*:4]` and `[#6X3:1]-[#7:2]-[#15:3]=[*:4]`, only differing by generic vs [#6X3] in position 1, seems fishy though not impossible. I wonder what we will find when we parameterize it afresh.

**Comment by davidlmobley** [comment]
@bannanc - I generally agree with where you are going here, and I actually DISAGREE with @cbayly13 somewhat because one can't simply "lose" certain parameters which aren't otherwise present (especially, the barrier height 0.1 case here) since otherwise, these get a generic parameter which involves a substantial barrier.

Does this suggest that the default generic torsion ought to be barrierless? Or, should we be introducing a generic that covers the extra case here? Maybe a generic torsion for `[*:1]~[#7:2]~[#15:3]~[*:4]` which is barrierless?

**Comment by bannanc** [comment]
@cbayly13 

>  It smells of overfitting as a consequence of too many atom types ...

I agree, there are A TON of sp2 nitrogen types and I'm having a really hard time grouping even the generic X-n-p-X options. It would be nice to have something for it though. I'm thinking about trying to find some molecules in eMolecules with bonds that match `[#7X2+0:1]~[#15:2]` and we have GAFF2 atomtypes for so I can see what torsion parameters they get then calling that good enough of an estimate for that case. 

> The fifth parameter (zero barrier height) is vestigial and should simply be tossed.

I want to make sure we're counting the same things are you saying:
```
[#6X3:1]-[#7:2]-[#15:3]=[*:4]  1    0.000         0.0            -3.         TorType=1
[#6X3:1]-[#7:2]-[#15:3]=[*:4]   1    2.300         0.0             1.         TorType=1
```
should be 
```
[#6X3:1]-[#7:2]-[#15:3]=[*:4]   1    2.300         0.0             1.         TorType=1
```
> one can't simply "lose" certain parameters which aren't otherwise present

@davidlmobley That ^ was my interpretation, I don't think we're losing the whole parameter, just removing one of the lines for it. It does otherwise have a barrier.

> Such a dramatic difference in torsion potential between [*:1]-[#7:2]-[#15:3]=[*:4] and [#6X3:1]-[#7:2]-[#15:3]=[*:4], only differing by generic vs [#6X3] in position 1, seems fishy though not impossible. I wonder what we will find when we parameterize it afresh.

I was trying to group the GAFF2 parameters we could just take the most generic case and keep just that.

**Comment by bannanc** [comment]
# Updated Recommendations 
```
[*:1]~[#7X3:2]-[#15:3]~[*:4]    1   2.5       180.000           2.000
[*:1]~[#7X4:2]-[#15:3]~[*:4]    1    0.1         0.000           3.000

[*:1]-[#7:2]-[#15:3]=[*:4]    1    3.000       180.0            -2.         TorType=1
[*:1]-[#7:2]-[#15:3]=[*:4]    1    2.300         0.0             3.         TorType=1

[#6X3:1]-[#7:2]-[#15:3]=[*:4]   1    2.300         0.0             1.         TorType=1
```

**Comment by cbayly13** [comment]
- The zero barrier height 3-fold torsion can be tossed because there is still the one-fold torsion following it; if the latter weren't there then there would be the problem you mentioned. 
- Regarding the second torsion in the list, which I was suggesting to remove:
`[*:1]~[#7X4:2]-[#15:3]~[*:4]    1    0.1         0.000           3.000`
you make a good point that a harmful generic torsion could end up being used instead. Is there a harmful generic torsion in this case? Back in the parm@Frosst days when I didn't know anything about a torsion I tended to use a zero torsion (counting on 1-4 electrostatics and vdW to do something) and I was assuming that here. So it is possible that the torsion in question should stay, although I would tend to zero it out until I found it was important.

**Comment by bannanc** [comment]
> Is there a harmful generic torsion in this case?

@cbayly13 These are THE ONLY N-P torsions right now! so if we remove any of them it will get a complete 't1' generic with the VERY HIGH generic. 
We could set it at 0.0, 
though it should be noted that the 0.1 is a rounded value between about 0.5 and 0.2 for the listed X-n4-p-X GAFF2 torsions listed above. 

----------------------

I am still missing N-P torsions for Nsp2 because I've had a hard time following all the GAFF2 atomtypes and there isn't an obvious way to group them. I'm going to have to find or make some molecules and GAFF2 type them, but it isn't going to happen tonight.

**Comment by davidlmobley** [comment]
OK, this sounds good to me so far, @bannanc , though obviously as you note we need to look at Nsp2-P torsions.

**Comment by bannanc** [comment]
Yes, I also imagine that N=P bonds also exist? I'm sure there are other "weird/corner" cases that we won't hit here.

**Comment by bannanc** [comment]
I'm not closing yet, but the Nsp3 are added in pull request #43

**Comment by bannanc** [comment]
Nsp3 covered in pull request #43 
Nsp2 added to issue #46
