### ISSUE TITLE
Parameters that should be more generic

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smirnoff99Frosst#34]
# N-N bond
There is an instance of a tetrahedral, positively charged nitrogen singly bonded to another nitrogen in drug bank that isn't currently typed. 

Here is the current N-N bond list in the smirffishFrcmod file:
```
[#7X3:1]-[#7X3:2]      380.  1.40    Frosst generic
[#7X3:1]-[#7X2:2]      340.  1.33    Frosst generic
[#7X2:1]-[#7X2:2]      340.  1.33    Frosst generic
```

My suggestion is that we make the first one more generic with `[#7:1]-[#7:2]` since the others will overwrite the first one anyway. 

Chemically I think the positively charged nitrogen would lead to a shorter/stronger bond, but this would give it a better guess than the generic bond for now.

**Comment by bannanc** [comment]
# C-O

There is a weird case in DrugBank with a trivalent oxygen (positively charged with 2 hydrogens). 
The first C-O bond in smirffish is 
```
[#6X4:1]-[#8X2:2]               320.0  1.410   parm99 aliphatic carbon-oxygen Csp3-O
```
Similar to above, I suggest we change the smirks string to `[#6:1]-[#8:2]` to keep it general enough to catch all C-O single bonds.

**Comment by bannanc** [comment]
# C#X bonds

There is another weird corner case, with [#6-1]#[#7+1] that is a nitrile group where the next bond is to the nitrogen not the carbon. 

There aren't many triple bonds in smirff99Frosst, I suggest we keep them more general, just to allow general coverage for the time being so change the following bonds so they don't use `X2` on the carbons:

```
[#6X2:1]#[#7:2]     350.0    1.188   Frosst C2-NL from C2-C2
[#6X2:1]#[#6X2:2]     350.0    1.188   Frosst C2-C2 RHF/6-31G(d,p) opt estimated force constant
```

**Comment by davidlmobley** [comment]
Sounds good in general, @bannanc . Would love to see a 2D structure or a SMILES of that positively charged oxygen though.

**Comment by bannanc** [comment]
@davidlmobley 
I have the positively charged oxygen structure somewhere in my notes, I'll add it to the relevant comment above tomorrow. 
I don't think it's very common, the only thing I can think of is some kind of alcohol in a VERY acidic environment. It looks like a structure an organic chemist would draw as some kind of transition state, not something that would be stable for very long.

**Comment by bannanc** [comment]
@davidlmobley - updated above with pictures

**Comment by bannanc** [comment]
# Angles for SX2 in aromatic rings 

This type of molecule:

<img width="450" alt="b809f2a3-d8b2-4170-8c9e-0b6675824367" src="https://cloud.githubusercontent.com/assets/11968541/24685250/2ec5a846-1961-11e7-9e93-905fecb2e998.png">

This gets assigned CB-S-CB in parm@frosst types:
```
CB-S -CB     62.000 94.500 From CA-S-NB; 4 May 2005
```
Which lines up pretty well with the `#16X2` generic angles:
```
[*:1]=[#16X2:2]=[*:3]    70.  180.    Frosst generic divalent hypervalent e.g. isothiocyanate
# divalent sulfur, both aliphatic and endocyclic in het5 (a la thiophene)
[*:1]-[#16X2,#16X3+1:2]-[*:3]  60.  98.     parm99 generic divalent sulfur
...
```
I propose we rearrange them so the generic can be for any bond the the double bond case is further down. 
```
# divalent sulfur, both aliphatic and endocyclic in het5 (a la thiophene)
[*:1]~[#16X2,#16X3+1:2]~[*:3]  60.  98.     parm99 generic divalent sulfur
[*:1]=[#16X2:2]=[*:3]    70.  180.    Frosst generic divalent hypervalent e.g. isothiocyanate
...
```

**Comment by bannanc** [comment]
all updated in pull request #43
