### ISSUE TITLE
Confusing angle in nitro like group

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smirnoff99Frosst#36]
There is only one angle still being assigned the generic in the filtered drugbank set, it looks like a nitro group, but the nitrogen is bound to three oxygens the third is divalent. Like the molecule below:

![ec2a3c43-54ce-4ec7-80fa-93535eb19f91](https://cloud.githubusercontent.com/assets/11968541/24531305/c57a8444-156c-11e7-89fe-473e2f8060a4.png)

I've been trying to think through what is "right" for this angle. We draw nitro groups with a neutral and negative oxygen, but really I would think of the `#8X1` oxygens as being equivalent, which means the angle to the "other oxygen" should more closely resemble the C-N-O angle in "normal" nitro groups. 

I'm going to see how those numbers compare in gaff right now...

**Comment by bannanc** [comment]
The molecules with these groups didn't make it to our gaff2 mol2 files for some reason. 

I suggest we update the nitro angle from:
```
[#6,#7,#8:1]-[#7X3:2](~[#8X1])~[#8X1:3]  70.000  117.700  Frosst CA-N2-O2 from fit to rhf/6-31G* from T.Halgren 1/26/99
```
This is a very specific angle and from what I can tell it doesn't change any of the other nitrogen centered angles.

**Comment by davidlmobley** [comment]
@bannanc - this seems reasonable to me, though with a prioritization for QM follow-up (e.g. the summer student should pull some molecules and look at whether this angle should be treated separately for `[#6]`, `[#7]`, and `[#8]`, probably.

**Comment by bannanc** [comment]
Added in pull request #43
