### ISSUE TITLE
torsions around Positively charged aromatic nitrogens

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smirnoff99Frosst#39]
There is a fairly common functional group in drugBank that has a tetravalent, aromatic nitrogen such as this molecule:

![b2daeacd-2ba1-4940-8928-944b0a2e9609](https://cloud.githubusercontent.com/assets/11968541/24637635/8fbb46ee-1897-11e7-8c03-c480d61cfe07.png)

We get generics for most of the relevant N:C bonds. 

I looks like they are assigned torsions that stem from a X-CA-NC-X in parm99 according to the notes in the frcmod.parm_frosst file

This is the parameter from the parm99.dat file:
```
X -CA-NC-X    2    9.60        180.0             2.         JCC,7,(1986),230
```

This seems to be the only similar torsion in the smirffishFrcmod file
```
[#6X3:1]:[#7X2:2]:[#6X3:3]:[#6X3:4]  1  4.800  180.0     2   Frosst generic
```

Given they're all aromatic, it seems logical for all of these to be planar with relatively high barriers. 
I don't feel comfortable making that SMIRKS more generic since it is in the middle of the N-C torsions and whatever I add seems to need to cover ring and non-ring bonds. It might be better to put something more generic further up, perhaps:

```
[*:1]~[#7a:2]:[#6a]~[*:4]   1    4.80   180.    2  CCB added corresponding to X_-CA-NC-X in parm99 JCC,7,(1986),230
```

@davidlmobley ( @cbayly13 if you have time this might be one that we could use your feedback on...)

**Comment by davidlmobley** [comment]
@bannanc - I like your proposed SMIRKS and the idea of adding it higher up as an additional generic, but let's see what @cbayly13 has to say if he can respond soon.

**Comment by cbayly13** [comment]
The other chemically sensible option is to extend the explicit torsion to include cationic trivalent aromatic nitrogens with:
`[#6X3:1]:[#7X2,#7X3+1:2]:[#6X3:3]:[#6X3:4]  1  4.800  180.0     2   Frosst generic`

**Comment by bannanc** [comment]
I'll look more carefully at that section, and make sure the generic isn't going to be overwritten. Maybe run a few tests.

**Comment by bannanc** [comment]
@cbayly13 
Right now, these are the first two torsions around N:C bonds:
```
[*:1]~[#7X2,#7X3$(*~[#8X1]):2]:[#6X3:3]~[*:4]  1  3.     180.0     2   Frosst generic
[#6X3:1]:[#7X2:2]:[#6X3:3]:[#6X3:4]  1  4.800  180.0     2   Frosst generic
```
So I think what we're proposing is to switch them and make the first one more generic:
```
[*:1]~[#7a:2]:[#6a:3]~[*:4]  1  4.800  180.0     2   Extra generic aromatic torsion
[*:1]~[#7X2,#7X3$(*~[#8X1]):2]:[#6X3:3]~[*:4]  1  3.     180.0     2   Frosst generic
```
Can you think of cases where `[*:1]~[#7X2,#7X3$(*~[#8X1]):2]:[#6X3:3]~[*:4]` would overwrite the generic when it shouldn't?

**Comment by bannanc** [comment]
It seems like removing this line
` [#6X3:1]:[#7X2:2]:[#6X3:3]:[#6X3:4]  1  4.800  180.0     2   Frosst generic` 
would cause that pattern 
`[#6X3:1]:[#7X2:2]:[#6X3:3]:[#6X3:4]` to always get this parameter: `1  3.     180.0     2   Frosst generic` 

I'm still getting used to torsions, but 4.8 seems significantly larger than 3, but are they different enough to need to parameters?

**Comment by bannanc** [comment]
These changes added in pull request #43
