### ISSUE TITLE
Change `[#1:1]-[#6X4]~[*;+1;+2]` to `[#1:1]-[#6X4]~[*+1,*+2]`

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smirnoff99Frosst#51]
@davidlmobley 
I was looking at "smirffishFrcmod.parm99Frosst.txt" for complicated SMIRKS patterns. I happened to find this line:
```
[#1:1]-[#6X4]~[*;+1;+2]  1.1000  0.0157  parm99 HP Veenstra et al JCC,8,(1992),963
```
While this is technically a valid SMIRKS string, I don't think it will match anything. `[*;+1;+2]` means any atom ('*') and (';') it has a '+1' charge and (';') it has a '+2' charge. As a single atom cannot have both a plus one and a plus two charge I don't think this will every match. 

Assuming it was supposed to be a tetrahedral carbon bound to a positively charged anything, I think the SMIRKS for the last atom needs to be `"[*+1,*+2]"`

**Comment by davidlmobley** [comment]
That looks right to me, @bannanc . In fact, I find this in one of the other intermediate archive files:
```
[#1:1]-[#6X4]~[*+1,*+2]  1.1000  0.0157  parm99 HP Veenstra et al JCC,8,(1992),963
```
which is exactly what you're proposing. It appears there was a typo introduced somehow/at some point.

**Comment by davidlmobley** [comment]
You should address this via a fix on openforcefield which is propagated to here.

**Comment by bannanc** [comment]
This was cloned by PR #52
