### ISSUE TITLE
XML tag

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smirnoff99Frosst#53]
@bannanc - I thought I'd fixed this at one point, but the XML tags here are back to using SMIRFF rather than SMIRNOFF. Can you check the conversion script on openforcefield repo and make sure it's inserting the correct tags, then get this switched to SMIRNOFF? (Both are recognized by ForceField during this transitional period)

**Comment by bannanc** [comment]
Yes, I'll look into this, it is probably the conversion script or the template.ffxml in openforcefield. I can add this to the open PR

**Comment by bannanc** [comment]
@davidlmobley 
I just got to looking at this, I'm not seeing SMIRFF anywhere, can you point to where the tag you were concerned about was?

**Comment by bannanc** [comment]
@davidlmobley 
Note - I realized today that I forgot to put the new smirff99Frosst into the openforcefield/data/forcefield/ directory, I'm going to open a separate pull request to fix that in the openforcefield repo. Is it possible that was the ffxml file you were looking at?

**Comment by davidlmobley** [comment]
Maybe, yes. I obviously messed something up as the word SMIRFF appears to not show up anywhere on this repo other than in issues, @bannanc . Sorry.
