### ISSUE TITLE
Change 'R' to 'x' to be RDKit compatible

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smirnoff99Frosst#54]
I will be migrating from using 'R' to 'x' in SMIRKS strings. In OpenEye language 'R' and 'x' both me number of ring bonds around an atom. With Daylight (and RDK) 'R' is number of rings an atom is a part of and 'x' is number of ring bonds. So changing 'R' to 'x' should not change the way molecules are typed with OpenEye tools, but should allow for more easy integration with RDKit. 

We will need to test that changes were made. I think the easiest way is to loop through the labels for the same molecules with the new and reference(current) smirnoff99Frosst and make sure each tuple gets the same pid assigned. I don't think this will take me too long. 

As far as location I think what makes the most sense is to create a `check_different_smirnoffs.ipynb` notebook in openforcefields/utilities/convert_frosst unless someone has a different place they would like to see it.

**Comment by davidlmobley** [comment]
Sounds like a good plan, @bannanc .

**Comment by jchodera** [comment]
It looks like there was a start at an [OpenSMARTS specification](https://github.com/timvdm/OpenSMARTS) but that seems to be stalled.

**Comment by bannanc** [comment]
Done with PR #57
