### ISSUE TITLE
README smirnoff typo

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smirnoff99Frosst#55]
The main README says "(smirnoff99frosst was formerly known as smirnoff99frosst)" under the conda install directions. 

I assume one of us did this when we were replacing smirff without thinking about the context. I'll fix it when I get the 'R'--> 'x' pull request ready.

**Comment by davidlmobley** [comment]
Ha, thanks.

**Comment by bannanc** [comment]
I fixed this is my last PR
